version: "3.7"
services:
  postgres:
    image: postgres:12.8
    container_name: poc_strapi
    environment:
      - POSTGRES_HOST=0.0.0.0
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=poc-strapi
    ports:
      - "5432:5432"
    volumes:
      - ~/docker_data_tmp/strapi/postgres-data:/var/lib/postgresql/data
